# Generated by Django 2.2 on 2020-11-02 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_app', '0002_cart_category_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(choices=[('CW', 'Casual Wear'), ('R', 'Running'), ('T', "Tennis Shoe's")], max_length=2),
        ),
    ]
