# Generated by Django 2.2 on 2020-11-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_app', '0004_auto_20201102_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shoe_type',
            field=models.CharField(choices=[('M', 'Casual Wear'), ('W', 'Running'), ('K', "Tennis Shoe's")], default='M', max_length=2),
            preserve_default=False,
        ),
    ]
