# Generated by Django 2.2 on 2020-11-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_app', '0005_product_shoe_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shoe_type',
            field=models.CharField(choices=[('M', 'Mens'), ('W', 'Women'), ('K', 'kids')], max_length=2),
        ),
    ]
