# Generated by Django 2.2 on 2020-11-05 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login_Reg_app', '0001_initial'),
        ('ecomm_app', '0006_auto_20201102_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='items_in_cart', to='Login_Reg_app.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cart',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='Login_Reg_app.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='shoe_type',
            field=models.CharField(choices=[('M', 'mens'), ('W', 'women'), ('K', 'kids')], max_length=2),
        ),
    ]
